#!/bin/bash
rm -rf status/*

docker run -d -ti -P -e STRATEGY='mmf' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.ETH-USDT' --name mmf_eth-usdt zenbot10
docker run -d -ti -P -e STRATEGY='mmf' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.EOS-USDT' --name mmf_eos-usdt zenbot10
docker run -d -ti -P -e STRATEGY='mmf' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.XRP-USDT' --name mmf_xrp-usdt zenbot10
docker run -d -ti -P -e STRATEGY='mmf' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.TRX-USDT' --name mmf_trx-usdt zenbot10
docker run -d -ti -P -e STRATEGY='mmf' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.LTC-USDT' --name mmf_ltc-usdt zenbot10
docker run -d -ti -P -e STRATEGY='mmf' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.BNB-USDT' --name mmf_bnb-usdt zenbot10

#docker run -d -ti -P -e STRATEGY='mmf_vol' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.ETH-USDT' --name mmf_vol_eth-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_vol' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.LTC-USDT' --name mmf_vol_ltc-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_vol' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.EOS-USDT' --name mmf_vol_eos-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_vol' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.TRX-USDT' --name mmf_vol_trx-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_vol' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.BNB-USDT' --name mmf_vol_bnb-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_vol' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.XRP-USDT' --name mmf_vol_xrp-usdt zenbot10

#docker run -d -ti -P -e STRATEGY='mmf_liq' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.ETH-USDT' --name mmf_eth-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_liq' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.LTC-USDT' --name mmf_ltc-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_liq' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.TRX-USDT' --name mmf_trx-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_liq' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.EOS-USDT' --name mmf_eos-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_liq' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.BNB-USDT' --name mmf_bnb-usdt zenbot10
#docker run -d -ti -P -e STRATEGY='mmf_liq' -v /root/zenbot/status:/opt/zenbot/status -e OPTSZEN='--status --reverse --interval_trade 5 --order_adjust_time 10000 --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000' -e SELECTOR='binance.XRP-USDT' --name mmf_xrp-usdt zenbot10
