#!/bin/bash
rm -rf status/*

pm2 start zenbot.js --name mmf_eth-usdt -- trade binance.ETH-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000 --period_length 7m --min_periods 15 --markdown_buy_pct 1.72 --markup_sell_pct 2.62 --order_type taker --trend_ema 4 --oversold_rsi_periods 14 --oversold_rsi 22
pm2 start zenbot.js --name mmf_ltc-usdt -- trade binance.LTC-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000 --period_length 7m --min_periods 15 --markdown_buy_pct 1.72 --markup_sell_pct 2.62 --order_type taker --trend_ema 4 --oversold_rsi_periods 14 --oversold_rsi 22
pm2 start zenbot.js --name mmf_trx-usdt -- trade binance.TRX-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000 --period_length 7m --min_periods 15 --markdown_buy_pct 1.72 --markup_sell_pct 2.62 --order_type taker --trend_ema 4 --oversold_rsi_periods 14 --oversold_rsi 22
pm2 start zenbot.js --name mmf_eos-usdt -- trade binance.EOS-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000 --period_length 7m --min_periods 15 --markdown_buy_pct 1.72 --markup_sell_pct 2.62 --order_type taker --trend_ema 4 --oversold_rsi_periods 14 --oversold_rsi 22
pm2 start zenbot.js --name mmf_bnb-usdt -- trade binance.BNB-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000 --period_length 7m --min_periods 15 --markdown_buy_pct 1.72 --markup_sell_pct 2.62 --order_type taker --trend_ema 4 --oversold_rsi_periods 14 --oversold_rsi 22
pm2 start zenbot.js --name mmf_xrp-usdt -- trade binance.XRP-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000 --period_length 7m --min_periods 15 --markdown_buy_pct 1.72 --markup_sell_pct 2.62 --order_type taker --trend_ema 4 --oversold_rsi_periods 14 --oversold_rsi 22

# pm2 start zenbot.js --name mmf_eth-usdt -- trade binance.ETH-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_ltc-usdt -- trade binance.LTC-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_trx-usdt -- trade binance.TRX-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_eos-usdt -- trade binance.EOS-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_bnb-usdt -- trade binance.BNB-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_xrp-usdt -- trade binance.XRP-USDT --strategy mmf_tmp2 --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 5 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000

# pm2 start zenbot.js --name mmf_eth-usdt -- trade binance.ETH-USDT --strategy mmf_tmp --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 10 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_ltc-usdt -- trade binance.LTC-USDT --strategy mmf_tmp --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 10 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_trx-usdt -- trade binance.TRX-USDT --strategy mmf_tmp --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 10 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_eos-usdt -- trade binance.EOS-USDT --strategy mmf_tmp --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 10 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_bnb-usdt -- trade binance.BNB-USDT --strategy mmf_tmp --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 10 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000
# pm2 start zenbot.js --name mmf_xrp-usdt -- trade binance.XRP-USDT --strategy mmf_tmp --status --reverse --sell_stop_pct 0.4 --profit_stop_enable_pct 0.5 --interval_trade 10 --order_adjust_time 10000 --sell_cancel_pct 0.2 --max_slippage_pct 0.05 --deposit 700 --order_poll_time 3000 --poll_trades 10000